# Generated by Django 3.2.5 on 2021-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-_IXHpBmStVsAnXqctN_3u_ZIGLToyS-VjSWonFQRFYObK9vq0DuCscC_LiJvzfHSdFY&usqp=CAU', max_length=500),
        ),
    ]
